version: "3.9"
services:
  postgresql:   
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=truequeando_db
      - POSTGRES_PASSWORD=dbp4assw0rd
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local